name: Xray

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build and test backend
        working-directory: backend
        run: ./mvnw clean test

      - name: Import results to Xray
        uses: mikepenz/xray-action@v3
        with:
          username: ${{ secrets.XRAY_ID }}
          password: ${{ secrets.XRAY_SECRET }}
          testformat: "junit"
          testpaths: "backend/target/surefire-reports/TEST-*.xml"
          projectkey: "PP"
