name: Upload Test Results to Xray

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  upload-to-xray:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu' # Alternative distribution options are available.

    - name: Build and run tests
      run: |
        ./mvnw clean test

    - name: Upload JUnit results to Xray
      run: |
        TOKEN_RESPONSE=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
          -H "Content-Type: application/json" \
          -d "{\"client_id\": \"${{ secrets.XRAY_ID }}\", \"client_secret\": \"${{ secrets.XRAY_SECRET }}\"}")
        TOKEN=$(echo $TOKEN_RESPONSE | tr -d '"')

        curl -X POST https://xray.cloud.getxray.app/api/v2/import/execution/junit \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer $TOKEN" \
          -F "file=@backend/target/surefire-reports/TEST-*.xml"

      env:
        XRAY_ID: ${{ secrets.XRAY_ID }}
        XRAY_SECRET: ${{ secrets.XRAY_SECRET }}
