name: Upload Test Results to Xray

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  upload-to-xray:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build and test
        working-directory: backend
        run: mvn clean test

      - name: Authenticate to Xray
        id: xray_auth
        run: |
          response=$(curl -s -X POST https://xray.cloud.getxray.app/api/v2/authenticate \
            -H "Content-Type: application/json" \
            -d "{\"client_id\": \"${{ secrets.XRAY_CLIENT_ID }}\", \"client_secret\": \"${{ secrets.XRAY_CLIENT_SECRET }}\"}")
          token=$(echo $response | tr -d '"')
          echo "token=$token" >> $GITHUB_OUTPUT

      - name: Upload test results to Xray
        run: |
          curl -X POST https://xray.cloud.getxray.app/api/v2/import/execution/junit \
            -H "Content-Type: multipart/form-data" \
            -H "Authorization: Bearer ${{ steps.xray_auth.outputs.token }}" \
            -F "file=@backend/target/surefire-reports/TEST-*.xml"